apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: picalc-pr-gitlabtest-
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  resources:
    - name: gitlab-source
      resourceRef:
        name: picalc-gitlab
  params:
    - name: pathToYamlFile
      value: "knative/picalc.yaml"
    - name: imageUrl
      value: 192.168.0.116:5000/picalc-gitlabtest
    - name: imageTag
      value: "1.0"
  serviceAccount: default
#  serviceAccount: tekton-triggers-admin
