apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: picalc
  namespace: getting-started
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: __IMAGE__
